export const countries = [
    { "country": "United States", "dial_code": "+1" },
    { "country": "Canada", "dial_code": "+1" },
    { "country": "Mexico", "dial_code": "+52" },
    { "country": "Brazil", "dial_code": "+55" },
    { "country": "Argentina", "dial_code": "+54" },
    { "country": "United Kingdom", "dial_code": "+44" },
    { "country": "France", "dial_code": "+33" },
    { "country": "Germany", "dial_code": "+49" },
    { "country": "Italy", "dial_code": "+39" },
    { "country": "Spain", "dial_code": "+34" },
    { "country": "Russia", "dial_code": "+7" },
    { "country": "China", "dial_code": "+86" },
    { "country": "India", "dial_code": "+91" },
    { "country": "Japan", "dial_code": "+81" },
    { "country": "South Korea", "dial_code": "+82" },
    { "country": "Australia", "dial_code": "+61" },
    { "country": "New Zealand", "dial_code": "+64" },
    { "country": "South Africa", "dial_code": "+27" },
    { "country": "Nigeria", "dial_code": "+234" },
    { "country": "Egypt", "dial_code": "+20" },
    { "country": "Turkey", "dial_code": "+90" },
    { "country": "Saudi Arabia", "dial_code": "+966" },
    { "country": "Israel", "dial_code": "+972" },
    { "country": "United Arab Emirates", "dial_code": "+971" },
    { "country": "Pakistan", "dial_code": "+92" },
    { "country": "Bangladesh", "dial_code": "+880" },
    { "country": "Indonesia", "dial_code": "+62" },
    { "country": "Vietnam", "dial_code": "+84" },
    { "country": "Thailand", "dial_code": "+66" },
    { "country": "Malaysia", "dial_code": "+60" },
    { "country": "Singapore", "dial_code": "+65" },
    { "country": "Philippines", "dial_code": "+63" },
    { "country": "Sri Lanka", "dial_code": "+94" },
    { "country": "Kenya", "dial_code": "+254" },
    { "country": "Ethiopia", "dial_code": "+251" },
    { "country": "Ghana", "dial_code": "+233" },
    { "country": "Morocco", "dial_code": "+212" },
    { "country": "Algeria", "dial_code": "+213" },
    { "country": "Ukraine", "dial_code": "+380" },
    { "country": "Poland", "dial_code": "+48" },
    { "country": "Netherlands", "dial_code": "+31" },
    { "country": "Belgium", "dial_code": "+32" },
    { "country": "Sweden", "dial_code": "+46" },
    { "country": "Norway", "dial_code": "+47" },
    { "country": "Denmark", "dial_code": "+45" },
    { "country": "Finland", "dial_code": "+358" },
    { "country": "Switzerland", "dial_code": "+41" },
    { "country": "Austria", "dial_code": "+43" },
    { "country": "Greece", "dial_code": "+30" }
]
